# ACCOUNT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
spec:
  #replicas: 1
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
        - name: account
          image: brunobrazil/account:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kube"
---
apiVersion: v1
kind: Service
metadata:
  name: account
spec:
  selector:
    app: account
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP