# CARD
apiVersion: apps/v1
kind: Deployment
metadata:
  name: card
spec:
  #replicas: 1
  selector:
    matchLabels:
      app: card
  template:
    metadata:
      labels:
        app: card
    spec:
      containers:
        - name: card
          image: brunobrazil/card:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kube"
---
apiVersion: v1
kind: Service
metadata:
  name: card
spec:
  selector:
    app: card
  ports:
    - port: 8085
      targetPort: 8085
  type: ClusterIP