# EUREKA
apiVersion: v1
kind: Service
metadata:
  name: eureka
spec:
  selector:
    app: eureka
  ports:
    - port: 8761
      targetPort: 8761
  type: ClusterIP
---

# ADDRESS
apiVersion: v1
kind: Service
metadata:
  name: address
spec:
  selector:
    app: address
  ports:
    - port: 8083
      targetPort: 8083
  type: ClusterIP
---

# CLIENT
apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  selector:
    app: client
  ports:
    - port: 8082
      targetPort: 8082
  type: ClusterIP
---

# ACCOUNT
apiVersion: v1
kind: Service
metadata:
  name: account
spec:
  selector:
    app: account
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP
---

# GATEWAY
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
  type: LoadBalancer